/**:
  ur_controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_arm_controller:
        type: franka_joint_trajectory_controller/JointTrajectoryController

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

      franka_hand_controller:
        type: position_controllers/GripperActionController

  franka_controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_arm_controller:
        type: franka_joint_trajectory_controller/JointTrajectoryController

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

      franka_hand_controller:
        type: position_controllers/GripperActionController


  ur_speed_scaling_state_broadcaster:
    ros__parameters:
      state_publish_rate: 100.0


  ur_force_torque_sensor_broadcaster:
    ros__parameters:
      sensor_name: tcp_fts_sensor
      state_interface_names:
        - force.x
        - force.y
        - force.z
        - torque.x
        - torque.y
        - torque.z
      frame_id: tool0
      topic_name: ft_data


  ur_joint_trajectory_controller:
    ros__parameters:
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.0
        goal_time: 0.0


  ur_scaled_joint_trajectory_controller:
    ros__parameters:
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0

  ur_gripper_controller:
    ros__parameters:
      joint: finger_joint
      action_monitor_rate: 20.0

  franka_robot_state_broadcaster:
    ros__parameters:
      arm_id: franka

  franka_arm_controller:
    ros__parameters:
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity
      joints:
        - franka_joint1
        - franka_joint2
        - franka_joint3
        - franka_joint4
        - franka_joint5
        - franka_joint6
        - franka_joint7
      gains:
        franka_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        franka_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        franka_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        franka_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        franka_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        franka_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        franka_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }

  franka_hand_controller:
    ros__parameters:
      joint: franka_finger_joint1

  
