/**:
  ros__parameters:
    # MoveIt uses this configuration for controller management
    trajectory_execution:
      allowed_execution_duration_scaling: 1.2
      allowed_goal_duration_margin: 0.5
      allowed_start_tolerance: 0.01
      trajectory_duration_monitoring: true

    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - franka/franka_effort_arm_controller
        - franka/franka_gripper
        # - franka_hand_controller
        - ur/scaled_joint_trajectory_controller
        # - ur_joint_trajectory_controller
        - ur/gripper_controller

      franka/franka_effort_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - franka_joint1
          - franka_joint2
          - franka_joint3
          - franka_joint4
          - franka_joint5
          - franka_joint6
          - franka_joint7

      franka/franka_gripper:
        action_ns: gripper_action
        type: GripperCommand
        default: true
        joints:
          - franka_finger_joint1
          - franka_finger_joint2

      franka/franka_hand_controller:
        action_ns: gripper_cmd
        default: true
        type: GripperCommand
        joints:
          - franka_finger_joint1

      ur/scaled_joint_trajectory_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - shoulder_pan_joint
          - shoulder_lift_joint
          - elbow_joint
          - wrist_1_joint
          - wrist_2_joint
          - wrist_3_joint


      ur/joint_trajectory_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: false
        joints:
          - shoulder_pan_joint
          - shoulder_lift_joint
          - elbow_joint
          - wrist_1_joint
          - wrist_2_joint
          - wrist_3_joint

      ur/gripper_controller:
        type: GripperCommand
        action_ns: gripper_cmd
        default: true
        parallel: true
        joints:
          - finger_joint